# Generated by Django 4.2.5 on 2023-11-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_portfolio_alter_student_major_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='UCCS Email')),
                ('major', models.CharField(choices=[('100', 'Begineer'), ('500', 'Intermediate'), ('1000', 'Pro')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.portfolio'),
        ),
    ]
