# Generated by Django 4.2.5 on 2023-11-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_user_remove_portfolio_is_active_delete_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
