# Generated by Django 4.2.5 on 2023-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_portfolio_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='major',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
    ]
