# Generated by Django 4.2.5 on 2023-11-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_rename_major_user_level_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
