# Generated by Django 4.2.5 on 2023-11-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0006_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('current_calorie', models.CharField(max_length=200)),
                ('heartbeat', models.CharField(max_length=200)),
                ('exercise_name', models.CharField(max_length=200)),
                ('exercise_reps', models.CharField(max_length=200)),
                ('exercise_goal', models.CharField(max_length=200)),
                ('user_grade', models.CharField(max_length=200)),
                ('exercise_relaxation', models.CharField(max_length=200)),
                ('portfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fitness_app.portfolio')),
            ],
        ),
    ]
