# Generated by Django 4.2.5 on 2023-11-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0008_user_matrix_remove_user_detail_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_matrix',
            name='name',
        ),
    ]
