# Generated by Django 4.2.5 on 2023-11-25 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness_app', '0010_remove_user_email_remove_user_name_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_matrix',
            name='Cuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
