# Generated by Django 4.2.5 on 2023-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0012_exercise_details_user_matrix_exercice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_matrix',
            name='exercise_goal',
        ),
        migrations.RemoveField(
            model_name='user_matrix',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='user_matrix',
            name='exercise_reps',
        ),
        migrations.AddField(
            model_name='exercise_details',
            name='exercise_details',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
