# Generated by Django 4.2.5 on 2023-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0013_remove_user_matrix_exercise_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_matrix',
            name='exercise_relaxation',
        ),
        migrations.AddField(
            model_name='exercise_details',
            name='exercise_relaxation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
