# Generated by Django 4.2.5 on 2023-11-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0014_remove_user_matrix_exercise_relaxation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_details',
            name='relexercise_details',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
